// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9dde858c-e58c-4659-bd4e-16e8c47c961a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XwgEJLPR6",
    "aws_user_pools_web_client_id": "12m3vakc6qb3r5todfrmfff48q",
    "oauth": {}
};


export default awsmobile;
